services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "${SQLSERVER_PORT}:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  
  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "${MAILPIT_SMTP_PORT}:1025"
      - "${MAILPIT_WEB_PORT}:8025"
    volumes:
      - mailpit_data:/data

volumes:
  postgres_data:
  sqlserver_data:
  redis_data:
  mailpit_data:
